### ISSUE TITLE
Sisfall dataset

### ISSUE THREAD

**Issue by sylchw** [ManuelCLopes/FallDetection_Model#1]
Hi there,

May I ask if you have instructions on how to use the sisfall dataset? It seems that the public link is broken
Wanted to ask about the data labels of the txt files, on what does each column represent.

Thanks!

-Sylvester

**Comment by ManuelCLopes** [comment]
Hi Sylvester,

The Sisfall dataset File name format is structured like this:
<ADL OR FALL_CODE>_<SUBJECT_ID>_<TRIAL_NO>.txt

For example a Activity Daily Activity file would look like "D17_SE04_R02", where "D17" is related to activity, "SE04" is related to what person was used to capture the sensor data, and "R02" is related to trial 02. 

Fall files look very the same, but the activity zone will be "Fxx" instead of "Dxx".

About the data:
"
Data were acquired with three sensors (2 accelerometers and 1 gyroscope) at a frequency sample of 200 Hz.

Each file contains nine columns and a different number of rows depending on the test length.

1st column is the acceleration data in the X axis measured by the sensor ADXL345.
2nd column is the acceleration data in the Y axis measured by the sensor ADXL345.
3rd column is the acceleration data in the Z axis measured by the sensor ADXL345.

4th column is the rotation data in the X axis measured by the sensor ITG3200.
5th column is the rotation data in the Y axis measured by the sensor ITG3200.
6th column is the rotation data in the Z axis measured by the sensor ITG3200.

7th column is the acceleration data in the X axis measured by the sensor MMA8451Q.
8th column is the acceleration data in the Y axis measured by the sensor MMA8451Q.
9th column is the acceleration data in the Z axis measured by the sensor MMA8451Q.
"
